/* eslint-disable */

import Login from "../../components/login/Login"
import "./terms.css"
import StateContext from "../../StateContext"
import DispatchContext from "../../DispatchContext"
import { useImmerReducer } from "use-immer"
import { useContext, useEffect } from "react"
import GetQuestionsUser from "../../components/getQuestionsUser/GetQuestionsUser"

function Terms() {
  const appState = useContext(StateContext)
  const appDispatch = useContext(DispatchContext)

  const initialState = {
    loading: true,
  }

  function ourReducer(draft, action) {
    switch (action.type) {
      case "loading":
        draft.loading = action.value
        return
    }
  }
  const [state, dispatch] = useImmerReducer(ourReducer, initialState)
  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])

  return (
    <div className="termsContainer">
      <div className="termsWrapper">
        <h2>TERMS OF USE</h2>
        <p>The present Terms of Use document is being published in accordance with the provisions of the Information Technology Act, 2000 and other applicable Rules thereunder, including but not limited to the Information Technology (Intermediary Guidelines) Rules, 2011. Welcome to the Qnots website ("the Website") and/or Qnots mobile app ("the App"). The Website and the App are owned and provided to you by B.Muniyandi, having residing at Dindigul, Tamilnadu - 624710. The Website and the App shall hereinafter be collectively referred to as "the Platform". For the purposes of this Terms of Use, accessing of the Platform together with any study material made available or uploaded therein or downloaded, embedded therefrom shall hereinafter be collectively be referred to as the "Services".</p>
        <h2>INTRODUCTION</h2>
        <p>By using or accessing the Platform in any way, including registering on the Platform, using, viewing, sharing, embedding and/or downloading any Services, you agree to be bound by the Terms of Use set forth herein. By accepting these Terms of Use, you also accept and agree to be bound by Qnots Policies, including but not limited to the Qnots Privacy Policy and the Qnots Copyright Policy. If you do not understand the present Terms of Use or do not agree with/accept any part thereof, you should immediately discontinue using or accessing the Platform. Your use and/or continued use of the Platform, as the case may be, amounts to express consent by you to the terms of this Terms of Use as well as other Qnots Policies.</p>
        <h2>ELIGIBILITY</h2>
        <p>By agreeing to these Terms of Use, you represent that you are legally competent to enter into an agreement and provide consent to these Terms of Use. You further represent that You are of sound mind. By agreeing to these Terms of Use, you represent that you are legally competent to enter into an agreement and provide consent to these Terms of Use. You further represent that Are not prohibited from entering into a legally binding contract as per applicable laws. In case the Platform is being accessed, and the Services are being availed for the benefit of a minor, you expressly confirm that you are legally competent to provide consent on behalf of such a minor and that the minor’s use of the Platform and/or the Services shall be subject to the Terms of Use.</p>
        <h2>YOUR ACCOUNT</h2>
        <p>You can become a registered user of the Platform by setting up a password-protected account with us. In order to set up such an account, you will be required to enter the details of your registered email id and password or you may login using the account details of any partner website. By setting up an account, you agree to accept any and all responsibility for any and all activities that occur under your account. By setting up the account, you further agree to the contents of the Privacy Policy. Qnots reserves the right and sole discretion to refuse access to the Platform, terminate any account, remove or restrict any content, at any time, with or without notice to you in case we notice any illegal activity on or from account or if we have reason to believe that any information provided by you is untrue, inaccurate, outdated or incomplete.</p>
        <h2>USER CONTENT</h2>
        <p>Qnots provides its users with the option of creating posts and/or upload content on the Platform ("User Content"). When you submit or upload any content on the Platform you represent and warrant that: You own all copyright in the content, or if you are not the owner, that you have permission to use the content, and that you have all the rights and permissions necessary to permit uploading, displaying, sharing, reproduction, downloading, the transmission of such content. The content you upload will not infringe the intellectual property rights or other rights of any person or entity, including but not limited to copyright, moral rights, trademark, patent or rights of privacy or publicity. Your use of the Platform will comply with all applicable laws, rules and regulations. The content does not contain material that defames or vilifies any person, people, races, religion or religious group and is not obscene, pornographic, indecent, harassing, threatening, harmful, invasive of privacy or publicity rights, abusive, inflammatory or otherwise objectionable. The content is not misleading and deceptive and does not offer or disseminating fraudulent goods, services, schemes, or promotions. Qnots reserves the right to review such content uploaded by the user and in case any content is found to be a violation of any of the Terms of Use and/or any applicable laws, Qnots may remove any content from the Platform and/or terminate or suspend the user account in its sole discretion.</p>
        <h2>RESTRICTION AND TERMINATION OF USE</h2>
        <p>Qnots may block, restrict, disable, suspend or terminate your access to all or part of the free Services offered on the Platform, at any time in Qnots's sole discretion, without prior notice to you upon Qnots. Specifically, in case of prolonged inactivity, Qnots reserves the right to disable, deactivate or terminate a user's account. If an account has been disabled or deactivated for inactivity, the user name associated with that account may be given to another user without notice to you or such other party. If you violate the Terms of Use, Qnots may at its sole discretion, block, restrict, disable, suspend or terminate the paid Services offered on the Platform.</p>
        <h2>INTELLECTUAL PROPERTY</h2>
        <p>The Services, including but not limited to digital content on the website i.e. text, graphics, user interface, images, video interface and software as well as their selection and arrangement, may belong to Qnots or to its partners who have granted Qnots the right to use their content and are protected to the fullest extent possible by applicable laws related to copyrights, trademarks, trade secrets and all other intellectual property and proprietary rights (collectively, "Intellectual Property Rights" ). Any unauthorized use of the Services may violate such laws and the Terms of Use. Qnots reserves all its legal rights to prohibit, stop or contain any such violations. You agree not to copy, republish, frame, download, transmit, modify, adapt, create derivative works based on, rent, lease, loan, sell, assign, distribute, display, perform, license, sublicense or reverse engineer the Platform and Services or any parts thereof or the selection and arrangement of the Platform and Services, except as expressly authorized herein. Qnots grants you a non-exclusive, non-transferable, limited permission to access and display the web pages within this Platform, solely on your computer or any other electronic viewing device for your personal, non-commercial use of this Platform. This permission is conditional on the basis that you shall not modify, alter or illegally use the content displayed on this Platform and shall keep intact and comply with all copyright, trademark, and other proprietary notices of the Platform, if any. The rights granted to you constitute a license and not a transfer of title in any manner. Use of the Platform or Services for any other purpose other than expressly granted hereunder is expressly prohibited and may result in severe civil and criminal penalties. In relation to any content submitted, uploaded or generated by you on the Platform, you hereby grant an unconditional, unlimited, perpetual, royalty-free, worldwide license and permission to Qnots and its affiliates, content sharing partners to display, store, host, publish, digitally reproduce or copy, transmit, communicate, modify, translate, distribute or otherwise make such content available on the Platform or in relation to the Services provided by Qnots. You agree that such content may continue to be made available on Qnots despite any termination or suspension of your account, if such content has been shared, stored or embedded by any other user(s). You agree not to hold Qnots responsible for the aforesaid activities in relation to your content.</p>
        <h2>ADVERTISEMENTS AND PROMOTIONS</h2>
        <p>This Platform may run advertisements and promotions from third parties, products and/or services in any manner and to any extent. Your communications, activities, relationships and business dealings with any third parties advertising or promoting via the Platform, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, shall be solely matters between you and such third parties. You acknowledge and agree that Qnots is not responsible or liable for any loss or damage of any kind incurred as a result of any such dealings or as the result of the presence of such non-Qnots advertisers on the Platform. Our links with advertisers should not be construed as an endorsement, approval or recommendation by us of the owners or operators of those linked websites, or of any information, graphics, materials, products or services referred to or contained on those linked websites, unless and to the extent stipulated to the contrary.</p>
        <h2>LINKS TO THIRD PARTY WEBSITES</h2>
        <p>The Platform may include links that redirect you to other websites. The Terms of Use do not cover these third party websites. You agree that once you leave our servers, any third party websites that you go to or interact with are at your own risk. Qnots shall not be held liable for any default, loss of function or any risk or consequence that you may be exposed to as a result of the same. The platform uses YouTube API Services. By using the platform, you are agreeing to YouTube Terms of Service. (https://www.youtube.com/t/terms) If the platform accesses or uses Authorized data (data that an active user expressly authorizes the platform to access or otherwise use via user credentials), in addition to the platform's normal procedure for deleting stored data, you can revoke that platform's access to your data via the Google security settings page at https://security.google.com/settings/security/permissions. You can also contact us at tbginfotech@gmail.com with questions or complaints about our privacy practices.</p>
        <h2>SPAM E-MAIL AND POSTINGS</h2>
        <p>In the event your access or use of the Platform and Services is found to be spammy, misleading, malicious, annoying or containing/promoting unsolicited e-mails or network postings, Qnots reserves its right to obtain immediate injunctive relief against you or against such use by you, in addition to all other remedies available at law or in equity. Qnots may also opt to block, filter or delete unsolicited emails, messages or postings as per its sole discretion.</p>
        <h2>INDEMNITY</h2>
        <p>You agree to indemnify, defend and hold Qnots and its officers, directors, partners, employees, agents and representatives harmless from and against any and all claims, damages, losses, liabilities, costs (including reasonable legal fees) or other expenses that arise directly or indirectly out of or from Your user content and any other content (e.g. computer viruses) that you may submit, post to or transmit through the Platform (including a third party's use of such user content (e.g. reliance on the accuracy, completeness or usefulness of your user content). Your access to or use of the Platform and Services (including any use by your employees, contractors or agents and all uses of your account numbers, usernames and passwords, whether or not actually or expressly authorised by you, in connection with the Platform and Services). Your breach of any clause of the ‘Terms of Use’. Any allegation that while using any of the software made available on the Platform you infringe or otherwise violate the copyright, trademark, trade secret or other intellectual property or other rights of any third party and/or any dealings between you and any third parties advertising or promoting or linked via the Platform. Your activities in connection with the Platform. This indemnity will be applicable without regard to the negligence of any party, including any indemnified person.</p>
        <h2>DISCLAIMER</h2>
        <p>We do not represent or guarantee that this Platform will be free from errors or viruses. You acknowledge that this Website may be affected by outages, faults or delays. Such outages, faults or delays may be caused by factors, including technical difficulties with the performance or operation of our or another person’s software, equipment or systems, traffic or technical problems with the Internet or infrastructure failures. We do not accept responsibility for any loss or damage, however caused (including through negligence), that you may directly or indirectly suffer in connection with your use of this Platform, nor do we accept any responsibility for any such loss arising out of your use of or reliance on information contained on or accessed through this Platform.</p>
        <h2>PRIVACY POLICY</h2>
        <p>Your privacy is important to us. Users of our Platform should refer to our Privacy Policy, which is incorporated into this Terms of Use by reference, with respect to the disclosure, collection, storage, usage and protection of your information during the course of your interaction with the Platform.</p>
        <h2>COPYRIGHT POLICY</h2>
        <p>Qnots respects and recognize the intellectual property rights of others and expects users of Qnots to do the same. Users of our Platform should refer to our Copyright Policy , which is incorporated into this Terms of Use by reference. If you believe that your content has been used on Qnots in a way that constitutes an infringement of your copyright, please notify Qnots’s designated agent for complaints or approach us through the procedure set out under the applicable provisions of the Information Technology Act. If you have a good faith belief that any of our users has infringed your copyright, you may follow the process as specified in our Copyright Policy.</p>
        <h2>AMENDMENTS TO THE TERMS AND CONDITIONS</h2>
        <p>Qnots may amend the Terms of Use and other Qnots Policies published on the Platform from time to time at its sole discretion. Your continued access or use of the Platform and the Services constitutes your acceptance of the amendments. Your access and use of the Platform and Services will be subject to the most current version of the Terms of Use, Privacy Policy and Copyright Policy posted on the Platform at the time of such use. Please regularly check the Platform to view the latest version of Qnots Policies.</p>
        <h2>APPLICABLE LAW AND JURISDICTION</h2>
        <p>Terms of Use shall be governed by and construed in accordance with the Laws of India. In case of any dispute, the courts in Dindigul will have exclusive jurisdiction to try any such disputes to the exclusion of all other courts.</p>
      </div>
    </div>
  )
}
export default Terms
